language: go

go:
  - 1.9
  - 1.10
  - tip

matrix:
  allow_failures:
      - go: top
    fast_finish: true

before_install:
  - go get github.com/golang/lint/golint
  - go get github.com/fzipp/gocyclo
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - make test-cover
  - goveralls -coverprofile=cover.out -service=travis-ci