[[constraint]]
    name = "github.com/stretchr/testify"
    version = "1.2.0"

[[constraint]]
    name = "pack.ag/amqp"
    branch = "channels"

[[constraint]]
    name = "github.com/Azure/azure-sdk-for-go"
    version = "12.2.0-beta"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"
