
[prune]
  go-tests = true
  unused-packages = true

[[override]]
    name = "pack.ag/amqp"
    source = "github.com/devigned/amqp"
    branch = "feature/session-filter"

[[constraint]]
    name = "github.com/Azure/azure-sdk-for-go"
    version = "15"

[[constraint]]
    name = "github.com/Azure/azure-amqp-common-go"
    version = "0.4"
