[[constraint]]
    name = "github.com/stretchr/testify"
    version = "1.2.0"

[[constraint]]
    name = "pack.ag/amqp"
    version = "0.3"

[[constraint]]
    name = "github.com/Azure/azure-sdk-for-go"
    version = "12.2.0-beta"